### ISSUE TITLE
Suggest Supporting the Default Laminar Cessna 172

### ISSUE THREAD

**Issue by wpostma** [N1K340/CrewPackXP#14]
I am contemplating doing a github fork on this repo to borrow what you have done so far and make the plugin able to work for a Cessna 172, or any default unrecognized ICAO, with less functionality, in particular just callouts during landing and takeoff.

If you don't think that's a good idea, I won't PR it to go back into your main repo.

**Comment by N1K340** [comment]
Yea, I guess there's some reasonability of that.
Word of warning if you're going to look too deeply at the code, I wouldn't say I know what I'm doing here, more bash stuff together till it works 😜

**Comment by wpostma** [comment]
Yeah, that's totally cool. I may never get anywhere with it, but starting from bashing around your stuff is easier for me than starting from scratch
